{% set version = "1.4.0" %}
{% set name = "Onassis" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 72798252fa267b5553052e846e04b3e0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.44.0,<1.46.0'
    - 'bioconductor-geometadb >=1.44.0,<1.46.0'
    - 'bioconductor-onassisjavalibs >=1.4.0,<1.6.0'
    - r-base
    - r-data.table
    - r-dt
    - r-knitr
    - r-rcurl
    - r-rjava
    - r-rsqlite
  run:
    - 'bioconductor-annotationdbi >=1.44.0,<1.46.0'
    - 'bioconductor-geometadb >=1.44.0,<1.46.0'
    - 'bioconductor-onassisjavalibs >=1.4.0,<1.6.0'
    - r-base
    - r-data.table
    - r-dt
    - r-knitr
    - r-rcurl
    - r-rjava
    - r-rsqlite
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'A package that allows the annotation of text with ontology terms (mainly from OBO ontologies) and the computation of semantic similarity measures based on the structure of the ontology between different annotated samples.'
