{% set version = "1.20.0" %}
{% set name = "RforProteomics" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: c2df3edec11e6ebf57e0c7b7c19c3e14
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocviews >=1.50.0,<1.52.0'
    - 'bioconductor-msnbase >=2.8.0,<2.10.0'
    - r-base
    - r-biocmanager
    - r-r.utils
    - r-shiny
  run:
    - 'bioconductor-biocviews >=1.50.0,<1.52.0'
    - 'bioconductor-msnbase >=2.8.0,<2.10.0'
    - r-base
    - r-biocmanager
    - r-r.utils
    - r-shiny
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package contains code to illustrate the ''Using R and Bioconductor for proteomics data analysis'' and ''Visualisation of proteomics data using R and Bioconductor'' manuscripts. The vignettes describe the code and data needed to reproduce the examples and figures described in the paper and functionality for proteomics visualisation. It also contain various function to discover R software for mass spectrometry and proteomics.'
