{% set version = "1.12.1" %}
{% set name = "sevenbridges" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: 65a35a8ef723b90c51ae57ebbd239879
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-curl
    - r-docopt
    - r-dplyr
    - r-httr
    - r-jsonlite
    - 'r-miniui >=0.1.1'
    - r-objectproperties
    - 'r-rstudioapi >=0.5'
    - 'r-shiny >=0.13'
    - r-stringr
    - r-uuid
    - r-yaml
  run:
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-curl
    - r-docopt
    - r-dplyr
    - r-httr
    - r-jsonlite
    - 'r-miniui >=0.1.1'
    - r-objectproperties
    - 'r-rstudioapi >=0.5'
    - 'r-shiny >=0.13'
    - r-stringr
    - r-uuid
    - r-yaml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Apache License 2.0 | file LICENSE'
  summary: 'R client and utilities for Seven Bridges platform API, from Cancer Genomics Cloud to other Seven Bridges supported platforms.'
