{% set version = "1.0.0" %}


package:
  name: bcool
  version: '{{version}}'

source:
  url: "https://github.com/Malfoy/BCOOL/archive/1.0.0.tar.gz"
  sha256: 1112e415f7b865e6321f6c448b53b7e0ce4f1c00471e136df2ad80df7859ef9f

build:
  number: 0
  skip: true # [osx]

requirements:
  run:
    - bgreat
    - ntcard
    - bcalm
    - btrim


test:
  commands:
    - bcool

about:
  home: https://github.com/Malfoy/BCOOL
  license: AGPL-3.0
  summary: BCOOL is a read corrector for NGS sequencing data that align reads on a de Bruijn graph. Version described at (https://arxiv.org/abs/1711.03336) presented at RECOMB-seq 2018
