{% set version = "2.50.1" %}
{% set name = "Biostrings" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a61189641d25f5a7bb17738198885ce4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-xvector >=0.22.0,<0.24.0'
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-xvector >=0.22.0,<0.24.0'
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Memory efficient string containers, string matching algorithms, and other utilities, for fast manipulation of large biological sequences or sets of sequences.'
extra:
  identifiers:
    - biotools:biostrings
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-biostrings
    path: recipes/bioconductor-biostrings
    version: 2.48.0
