{% set version = "2.6.0" %}
{% set name = "chipenrich.data" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: cd762813ed7fcc7e0ef6d0be7de5047b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.44.0,<1.46.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.44.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-readr
  run:
    - 'bioconductor-annotationdbi >=1.44.0,<1.46.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.44.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-readr
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-3
  summary: 'Supporting data for the chipenrich package. Includes pre-defined gene sets, gene locus definitions, and mappability estimates.'
