{% set name = "diamond_add_taxonomy" %}
{% set version = "0.1.1" %}
{% set sha256 = "6d34104ac24847da8940a978459600da3a177af862947e2bc23fcea7c280f1f0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pvanheus/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install --no-deps . -vvv"
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - ete3
  
test:
  commands:
   - diamond_add_taxonomy --help |grep DIAMOND_OUTPUT_FILE >/dev/null 2>&1

about:
  home: https://github.com/pvanheus/diamond_add_taxonomy
  summary: 'Utility to work with NCBI taxonomy database including tool to annotate DIAMOND results with taxonomy lineage'
  license: MIT
extra:
  container:
    # click needs locale
    extended-base: True
  recipe-maintainers:
    - pvanheus
