package:
  name: grid
  version: "1.1"

build:
  skip: True  # [osx]
<<<<<<< HEAD
  number: 3

source:
  url: https://github.com/ohlab/GRiD/archive/1.1.tar.gz
  sha256: 85db19227e0cc988f55e246368443509ea757981e174a5508c4491d5b5f2a62b

=======
  number: 2

source:
  url: https://github.com/ohlab/GRiD/archive/1.1.tar.gz
  sha256: d0cf0fc2407d4678e38c3bf9f895771d73a67505b9f27b065692785186b88b3f
 
>>>>>>> 01ede2b0ddea31ab208eec38c527acc9253a3f48
requirements:
  run:
    - parallel
    - pathoscope
    - r-dplyr
    - r-ggplot2
    - r-gplots
    - r-getopt
    - r-gsubfn
    - samtools
    - bamtools
    - bowtie2
    - seqtk
    - bedtools
    - blast
    - mosdepth
    - readline>=6.2

test:
  commands:
    - grid -h
    - update_database -h 

about:
  home: https://github.com/ohlab/GRiD
  license: MIT
  summary: Growth Rate Index (GRiD) measures bacterial growth rate from reference genomes (including draft quality genomes) and metagenomic bins at ultra-low sequencing coverage (> 0.2x).
