{% set name = "metawrap" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/bxlab/metaWRAP/archive/v{{ version }}.tar.gz
  md5: face9197bb696b037d7b2acdf27c668a

build:
  number: 0
  skip: True # [osx]

requirements:
  build: 

  run:
    - bcftools
    - biopython
    - blast >=2.7.1 
    - bmfilter >=3.101 1
    - bmtagger >=3.101 3
    - bmtool >=3.101 1
    - boost >=1.64.0
    - boost-cpp 1.64.0
    - bowtie2 >=2.3.0
    - bwa >=0.7.15
    - cairo >=1.14.8
    - checkm-genome >=1.0.7 py27_0
    - concoct 0.4.0 gsl1.16_0
    - cryptography >=2.1.4
    - cutadapt >=1.15
    - cython >=0.27.3
    - fastqc >=0.11.5
    - ggplot 0.6.8 py27_0
    - gnutls >=3.5.15
    - icu 58.2
    - jellyfish >=1.1.11
    - kraken >=0.10
    - krona
    - matplotlib
    - maxbin2 >=2.2
    - megahit >=1.1.2
    - metabat2 >=2.12.1
    - minced
    - numpy
    - openjdk
    - pandas
    - perl >=5
    - perl-bioperl >=1.6.924
    - pip
    - pplacer >=1.1.alpha17
    - prokka >=1.12
    - python >=2.7.11
    - qt >=4.8.5
    - quast >=4.1
    - readline
    - salmon >=0.9.1
    - samtools >=1.6
    - scikit-learn
    - scipy
    - seaborn >=0.8.1
    - spades >=3
    - srprism >=2.4.24
    - subprocess32 >=3.2.7
    - taxator-tk 1.3.3e
    - tk 8.5.18
    - trim-galore >=0.4.5
    - r-recommended >=3.3.2
    - r-ggplot2 >=2.2.1
    - xorg-libxrender

test:
  commands:
    - metawrap -h
    - metawrap read_qc -h
    - which config-metawrap

about:
  home: https://github.com/bxlab/metaWRAP
  license: MIT
  summary: "MetaWRAP is a pipeline for genome-resolved metagenomic data analysis"


