{% set version = "2.6.0" %}
{% set name = "ELMER" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 0b7c4cc368c1c6b6e841e1734db91761
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biomart >=2.38.0,<2.40.0'
    - 'bioconductor-complexheatmap >=1.20.0,<1.22.0'
    - 'bioconductor-elmer.data >=2.6.0,<2.8.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-gviz >=1.26.0,<1.28.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-multiassayexperiment >=1.8.0,<1.10.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - 'bioconductor-tcgabiolinks >=2.10.0,<2.12.0'
    - r-base
    - r-circlize
    - r-doparallel
    - r-downloader
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-gridextra
    - r-lattice
    - r-magrittr
    - r-matrix
    - r-plotly
    - r-plyr
    - r-readr
    - r-reshape
    - r-rmarkdown
    - r-rvest
    - r-stringr
    - r-xml2
  run:
    - 'bioconductor-biomart >=2.38.0,<2.40.0'
    - 'bioconductor-complexheatmap >=1.20.0,<1.22.0'
    - 'bioconductor-elmer.data >=2.6.0,<2.8.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-gviz >=1.26.0,<1.28.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-multiassayexperiment >=1.8.0,<1.10.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - 'bioconductor-tcgabiolinks >=2.10.0,<2.12.0'
    - r-base
    - r-circlize
    - r-doparallel
    - r-downloader
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-gridextra
    - r-lattice
    - r-magrittr
    - r-matrix
    - r-plotly
    - r-plyr
    - r-readr
    - r-reshape
    - r-rmarkdown
    - r-rvest
    - r-stringr
    - r-xml2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'ELMER is designed to use DNA methylation and gene expression from a large number of samples to infere regulatory element landscape and transcription factor network in primary tissue.'
extra:
  parent_recipe:
    name: bioconductor-elmer
    path: recipes/bioconductor-elmer
    version: 2.4.4
